channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - numpy
  - xarray
  - rasterio
  - yaml
  - pyyaml
  - earthengine-api
  - netcdf4
  - scikit-learn
  - scipy
  - ruamel_yaml
  - rioxarray
  - dask
  - requests
  - tqdm
  # river-regulation dependencies
  - dataretrieval
  - jupyterlab
  - geopandas >= 0.12
  - cartopy
  - pygeos
  - landlab
  - ipywidgets
  # precip-analysis dependencies
  - Boto3
  # visualization dependencies
  - matplotlib<=3.5.2
  - geoviews
  - holoviews
  - bokeh
  - pip:
    - geonetworkx