channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pandas
  - numpy
  - xarray
  - rasterio
  - rioxarray
  - netcdf4
  - dask
  - geopandas
  - cartopy
  - pytest
  - conda-build
  - pip:
    - geonetworkx