channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - numpy
  - xarray
  - rasterio
  - yaml
  - pyyaml
  - earthengine-api
  - netcdf4
  - scikit-learn
  - scipy
  - ruamel_yaml
  - rioxarray
  - dask
  - requests
  - tqdm
  # river-regulation dependencies
  - dataretrieval
  - jupyterlab
  - matplotlib<=3.5.2
  - geopandas >= 0.12
  - cartopy
  - pygeos
  - landlab