channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - xarray
  - geopandas >= 0.10
  - rasterio
  - yaml
  - pyyaml
  - earthengine-api
  - netcdf4
  - scikit-learn
  - scipy
  - ruamel_yaml
  - rioxarray
  - dask
  - requests
  - shapely
  - cartopy
  - tqdm
  # river-regulation dependencies
  - dataretrieval
  - jupyterlab
  - matplotlib=3.5.2