channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pandas
  - numpy
  - xarray
  - rasterio
  - yaml
  - pyyaml
  - earthengine-api
  - netcdf4
  - scikit-learn
  - scipy
  - ruamel_yaml
  - rioxarray
  - dask
  - requests
  - tqdm
  # river-regulation dependencies
  - dataretrieval
  - jupyterlab
  - geopandas
  - cartopy
  - landlab
  - ipywidgets
  - openpyxl
  # precip-analysis dependencies
  - Boto3
  # visualization dependencies
  - matplotlib
  - geoviews
  - holoviews
  - bokeh
  - jupyter_bokeh
  - hvplot
  - panel
  - param
  - selenium
  # development
  - conda-build
  - pip:
    - geonetworkx