channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.6
  - pandas
  - numpy
  - xarray
  - geopandas >= 0.10
  - rasterio
  - yaml
  - pyyaml
  - earthengine-api
  - netcdf4
  - scikit-learn
  - scipy
  - ruamel_yaml
  - rioxarray
  - dask
  - requests
  - shapely
  - cartopy