site_name: ResORR
site_description: Reservoir Operations driven River Regulation
site_author: Pritam Das @ SASWE, University of Washington
repo_url: https://github.com/UW-SASWE/ResORR
theme:
  name: readthedocs

nav:
  - Home: index.md
  - How to run ResORR:
    - Network Generation: methods/01-Network-Generation-networkx.ipynb
    - Run ResORR model: methods/02-Regulation.ipynb

plugins:
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      execute: false